#!/usr/bin/env bash
# Create a symbolic link to this file in .git/hooks

mainline_toc=$(head -n 1 EventTracker_Mainline.toc | cut -d ' ' -f 3)
retail_toc=$(head -n 1 EventTracker.toc | cut -d ' ' -f 3)
wotlk_toc=$(head -n 1 EventTracker_Wrath.toc | cut -d ' ' -f 3)

error=0

if [ "$mainline_toc" != "$retail_toc" ]; then
    echo "EventTracker_Mainline.toc & EventTracker.toc have different Interface values"
    echo "$mainline_toc <> $retail_toc"
    echo
    error=1
fi

mainline_addon_version=$(head -n 3 EventTracker_Mainline.toc | tail -n 1 | cut -d ' ' -f 3)
retail_addon_version=$(head -n 3 EventTracker.toc | tail -n 1 | cut -d ' ' -f 3)
wotlk_addon_version=$(head -n 3 EventTracker_Wrath.toc | tail -n 1 | cut -d ' ' -f 3)

if [ "$mainline_addon_version" != "$wotlk_addon_version" ]; then
    echo "Addon version mismatch between WOTLK and Retail: $wotlk_addon_version <> $mainline_addon_version"
    echo
    error=1
fi

if [ "$mainline_addon_version" != "$retail_addon_version" ]; then
    echo "Addon version mismatch between EventTracker_Mainline.toc"
    echo "and EventTracker.toc: $mainline_addon_version <> $retail_addon_version"
    error=1
fi

for file in $(git diff --name-only --cached); do
    # (^.*--@(end-)?debug[^@])|(^.*--(end-)?debug@)|(^\s*\S+.*--@(end-)?debug@)|(^.*--\s+@(end-)?debug)|(^.*--\s+(end-)?debug)
    if grep -P '^(\s*\S+.*--@(end-)?debug@)|(.*--@(end-)?debug(?:(((?!@).)+|\b)))+$' "$file"; then
        grep --with-filename -n -P '^(\s*\S+.*--@(end-)?debug@)|(.*--@(end-)?debug(?:(((?!@).)+|\b)))+$' "$file"
        echo -e "\033[0;31mThere is at least one typo with @debug@/@end-debug@"
        echo ""
        error=1
        break
    fi
done

exit $error
