#!/usr/bin/env bash
# Create a symbolic link to this file in .git/hooks

GREEN=$'\e[1;32m'
RED=$'\e[0;31m'
CYAN=$'\e[1;34m'
GRAY=$'\e[1;33m'
NC=$'\e[0m'

mainline_toc=$(head -n 1 EventTracker_Mainline.toc | cut -d ' ' -f 3)
retail_toc=$(head -n 1 EventTracker.toc | cut -d ' ' -f 3)
wotlk_toc=$(head -n 1 EventTracker_Wrath.toc | cut -d ' ' -f 3)

error=0

if [ "$mainline_toc" != "$retail_toc" ]; then
    echo "EventTracker_Mainline.toc & EventTracker.toc have different Interface values"
    echo "$mainline_toc <> $retail_toc"
    echo
    error=1
fi

mainline_addon_version=$(head -n 3 EventTracker_Mainline.toc | tail -n 1 | cut -d ' ' -f 3)
retail_addon_version=$(head -n 3 EventTracker.toc | tail -n 1 | cut -d ' ' -f 3)
wotlk_addon_version=$(head -n 3 EventTracker_Wrath.toc | tail -n 1 | cut -d ' ' -f 3)

if [ "$mainline_addon_version" != "$wotlk_addon_version" ]; then
    echo "Addon version mismatch between WOTLK and Retail: $wotlk_addon_version <> $mainline_addon_version"
    echo
    error=1
fi

if [ "$mainline_addon_version" != "$retail_addon_version" ]; then
    echo "Addon version mismatch between EventTracker_Mainline.toc"
    echo "and EventTracker.toc: $mainline_addon_version <> $retail_addon_version"
    error=1
fi

if type ggrep >/dev/null 2>&1; then
    grep_prog=ggrep
else
    # shellcheck disable=2209
    grep_prog=grep
fi

pat='(\s*--\s+@?(end-)?debug@?)|(\s*--\s*(end-)?debug@?)|(\s*\S+.*--@(end-)?debug@)|(\s*--@(end-)?debug[\s\S]+@)|(--@\s+(end-)?debug@)|(\s*--\s+@(end-)?debug@)|(--\s*@(end-)?debug(?:(((?!@).)+|\b)))$'
for file in $(git diff --name-only --cached); do
    if [[ $file != *.lua ]]; then
        echo -e "${GRAY}Skipping${NC} @debug@ sanity checks for$CYAN $file $NC"
        continue
    fi
    echo -e "Checking '@debug@' sanity checks for $CYAN$file $NC"
    if "$grep_prog" -qP "$pat" "$file"; then
        "$grep_prog" --color=always --with-filename -n -P "$pat" "$file"
        echo " "
        error=2
    fi
done

if [[ "$error" == 2 ]]; then
    echo " "
    echo -e "\033[0;31mThere is at least one typo with @debug@/@end-debug@"
fi

luarocks_prog="$HOME"/.luarocks/bin/luacheck
[ -f "$luarocks_prog" ] || luarocks_prog=luacheck

printf "\nChecking lua lints...\n"
while IFS= read -rd $'\0' fn; do
    if "$luarocks_prog" --no-color -q "$fn" >/dev/null; then
        echo "luacheck: $fn ${GREEN}OK!${NC}"
    else
        echo "luacheck: $fn ${RED}FAILED!${NC} Fix the issue before re-committing."
        error=3
    fi
done < <(find  . -type f -name '*.lua' -print0)

exit $error
